"""user tokens

Revision ID: 55d585fc03bc
Revises: 5c0711092e8c
Create Date: 2022-01-17 16:27:24.184207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55d585fc03bc'
down_revision = '5c0711092e8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('administrator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('tokenDauer', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_administrator_token'), ['token'], unique=True)

    with op.batch_alter_table('mitarbeiter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('tokenDauer', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_mitarbeiter_token'), ['token'], unique=True)

    with op.batch_alter_table('wartung', schema=None) as batch_op:
        batch_op.drop_index('ix_wartung_bis')
        batch_op.drop_index('ix_wartung_von')

    with op.batch_alter_table('wartungspersonal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('tokenDauer', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_wartungspersonal_token'), ['token'], unique=True)

    with op.batch_alter_table('zugpersonal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('tokenDauer', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_zugpersonal_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zugpersonal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zugpersonal_token'))
        batch_op.drop_column('tokenDauer')
        batch_op.drop_column('token')

    with op.batch_alter_table('wartungspersonal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wartungspersonal_token'))
        batch_op.drop_column('tokenDauer')
        batch_op.drop_column('token')

    with op.batch_alter_table('wartung', schema=None) as batch_op:
        batch_op.create_index('ix_wartung_von', ['von'], unique=False)
        batch_op.create_index('ix_wartung_bis', ['bis'], unique=False)

    with op.batch_alter_table('mitarbeiter', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mitarbeiter_token'))
        batch_op.drop_column('tokenDauer')
        batch_op.drop_column('token')

    with op.batch_alter_table('administrator', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_administrator_token'))
        batch_op.drop_column('tokenDauer')
        batch_op.drop_column('token')

    # ### end Alembic commands ###
