"""Löschen des Cascade constraints (all, delete) in der Tabelle Wartungspersonal

Revision ID: 5c0711092e8c
Revises: 6fbe5bd4f761
Create Date: 2022-01-05 15:59:09.233563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c0711092e8c'
down_revision = '6fbe5bd4f761'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zug', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_zug_triebwagen_nr'), ['triebwagen_nr'])
        batch_op.drop_constraint('fk_zug_triebwagen_nr_triebwagen', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_zug_triebwagen_nr_triebwagen'), 'triebwagen', ['triebwagen_nr'], ['nr'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zug', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_zug_triebwagen_nr_triebwagen'), type_='foreignkey')
        batch_op.create_foreign_key('fk_zug_triebwagen_nr_triebwagen', 'triebwagen', ['triebwagen_nr'], ['nr'], onupdate='CASCADE')
        batch_op.drop_constraint(batch_op.f('uq_zug_triebwagen_nr'), type_='unique')

    # ### end Alembic commands ###
