"""Erstellen von Constraints und allen Klassen

Revision ID: 7407ef04ee4e
Revises: 
Create Date: 2021-12-30 20:11:54.851965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7407ef04ee4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrator',
    sa.Column('mitarbeiterNr', sa.Integer(), nullable=False),
    sa.Column('svnr', sa.Integer(), nullable=False),
    sa.Column('vorname', sa.String(length=255), nullable=False),
    sa.Column('nachname', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('passwort', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('mitarbeiterNr', name=op.f('pk_administrator'))
    )
    with op.batch_alter_table('administrator', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_administrator_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_administrator_svnr'), ['svnr'], unique=True)

    op.create_table('mitarbeiter',
    sa.Column('mitarbeiterNr', sa.Integer(), nullable=False),
    sa.Column('svnr', sa.Integer(), nullable=False),
    sa.Column('vorname', sa.String(length=255), nullable=False),
    sa.Column('nachname', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('passwort', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('mitarbeiterNr', name=op.f('pk_mitarbeiter'))
    )
    with op.batch_alter_table('mitarbeiter', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mitarbeiter_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_mitarbeiter_svnr'), ['svnr'], unique=True)

    op.create_table('wagen',
    sa.Column('nr', sa.Integer(), nullable=False),
    sa.Column('spurweite', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('nr', name=op.f('pk_wagen'))
    )
    with op.batch_alter_table('wagen', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wagen_spurweite'), ['spurweite'], unique=False)

    op.create_table('wartungspersonal',
    sa.Column('mitarbeiterNr', sa.Integer(), nullable=False),
    sa.Column('svnr', sa.Integer(), nullable=False),
    sa.Column('vorname', sa.String(length=255), nullable=False),
    sa.Column('nachname', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('passwort', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('mitarbeiterNr', name=op.f('pk_wartungspersonal'))
    )
    with op.batch_alter_table('wartungspersonal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wartungspersonal_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_wartungspersonal_svnr'), ['svnr'], unique=True)

    op.create_table('zug',
    sa.Column('nr', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('nr', name=op.f('pk_zug'))
    )
    op.create_table('personenwagen',
    sa.Column('nr', sa.Integer(), nullable=False),
    sa.Column('spurweite', sa.Integer(), nullable=False),
    sa.Column('sitzanzahl', sa.Integer(), nullable=False),
    sa.Column('maximalgewicht', sa.Integer(), nullable=False),
    sa.Column('zugNr', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['zugNr'], ['zug.nr'], name=op.f('fk_personenwagen_zugNr_zug'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('nr', name=op.f('pk_personenwagen'))
    )
    with op.batch_alter_table('personenwagen', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_personenwagen_spurweite'), ['spurweite'], unique=False)

    op.create_table('triebwagen',
    sa.Column('nr', sa.Integer(), nullable=False),
    sa.Column('spurweite', sa.Integer(), nullable=False),
    sa.Column('maxZugkraft', sa.Integer(), nullable=False),
    sa.Column('zugNr', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['zugNr'], ['zug.nr'], name=op.f('fk_triebwagen_zugNr_zug'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('nr', name=op.f('pk_triebwagen'))
    )
    with op.batch_alter_table('triebwagen', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_triebwagen_spurweite'), ['spurweite'], unique=False)

    op.create_table('wartung',
    sa.Column('wartungsNr', sa.Integer(), nullable=False),
    sa.Column('von', sa.DateTime(), nullable=False),
    sa.Column('bis', sa.DateTime(), nullable=False),
    sa.Column('zugNr', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['zugNr'], ['zug.nr'], name=op.f('fk_wartung_zugNr_zug'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('wartungsNr', name=op.f('pk_wartung'))
    )
    with op.batch_alter_table('wartung', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wartung_bis'), ['bis'], unique=False)
        batch_op.create_index(batch_op.f('ix_wartung_von'), ['von'], unique=False)

    op.create_table('zugpersonal',
    sa.Column('mitarbeiterNr', sa.Integer(), nullable=False),
    sa.Column('svnr', sa.Integer(), nullable=False),
    sa.Column('vorname', sa.String(length=255), nullable=False),
    sa.Column('nachname', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('passwort', sa.String(length=128), nullable=False),
    sa.Column('berufsbezeichnung', sa.String(length=255), nullable=False),
    sa.Column('zugNr', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['zugNr'], ['zug.nr'], name=op.f('fk_zugpersonal_zugNr_zug')),
    sa.PrimaryKeyConstraint('mitarbeiterNr', name=op.f('pk_zugpersonal'))
    )
    with op.batch_alter_table('zugpersonal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zugpersonal_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_zugpersonal_svnr'), ['svnr'], unique=True)

    op.create_table('ist_zugeteilt',
    sa.Column('wartungspersonal_id', sa.Integer(), nullable=True),
    sa.Column('wartung_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['wartung_id'], ['wartung.wartungsNr'], name=op.f('fk_ist_zugeteilt_wartung_id_wartung'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wartungspersonal_id'], ['wartungspersonal.mitarbeiterNr'], name=op.f('fk_ist_zugeteilt_wartungspersonal_id_wartungspersonal'), onupdate='CASCADE', ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ist_zugeteilt')
    with op.batch_alter_table('zugpersonal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zugpersonal_svnr'))
        batch_op.drop_index(batch_op.f('ix_zugpersonal_email'))

    op.drop_table('zugpersonal')
    with op.batch_alter_table('wartung', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wartung_von'))
        batch_op.drop_index(batch_op.f('ix_wartung_bis'))

    op.drop_table('wartung')
    with op.batch_alter_table('triebwagen', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_triebwagen_spurweite'))

    op.drop_table('triebwagen')
    with op.batch_alter_table('personenwagen', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_personenwagen_spurweite'))

    op.drop_table('personenwagen')
    op.drop_table('zug')
    with op.batch_alter_table('wartungspersonal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wartungspersonal_svnr'))
        batch_op.drop_index(batch_op.f('ix_wartungspersonal_email'))

    op.drop_table('wartungspersonal')
    with op.batch_alter_table('wagen', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wagen_spurweite'))

    op.drop_table('wagen')
    with op.batch_alter_table('mitarbeiter', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mitarbeiter_svnr'))
        batch_op.drop_index(batch_op.f('ix_mitarbeiter_email'))

    op.drop_table('mitarbeiter')
    with op.batch_alter_table('administrator', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_administrator_svnr'))
        batch_op.drop_index(batch_op.f('ix_administrator_email'))

    op.drop_table('administrator')
    # ### end Alembic commands ###
