"""Klassenimplementierungen wurden hinzugefügt

Revision ID: 9053b297cad0
Revises: 
Create Date: 2021-12-25 01:19:55.303590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9053b297cad0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrator',
    sa.Column('mitarbeiterNr', sa.Integer(), nullable=False),
    sa.Column('svnr', sa.Integer(), nullable=False),
    sa.Column('vorname', sa.String(length=255), nullable=False),
    sa.Column('nachname', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('passwort', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('mitarbeiterNr')
    )
    with op.batch_alter_table('administrator', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_administrator_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_administrator_svnr'), ['svnr'], unique=True)

    op.create_table('mitarbeiter',
    sa.Column('mitarbeiterNr', sa.Integer(), nullable=False),
    sa.Column('svnr', sa.Integer(), nullable=False),
    sa.Column('vorname', sa.String(length=255), nullable=False),
    sa.Column('nachname', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('passwort', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('mitarbeiterNr')
    )
    with op.batch_alter_table('mitarbeiter', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mitarbeiter_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_mitarbeiter_svnr'), ['svnr'], unique=True)

    op.create_table('personenwagen',
    sa.Column('nr', sa.Integer(), nullable=False),
    sa.Column('spurweite', sa.Integer(), nullable=False),
    sa.Column('sitzanzahl', sa.Integer(), nullable=False),
    sa.Column('maximalgewicht', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('nr')
    )
    with op.batch_alter_table('personenwagen', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_personenwagen_spurweite'), ['spurweite'], unique=False)

    op.create_table('triebwagen',
    sa.Column('nr', sa.Integer(), nullable=False),
    sa.Column('spurweite', sa.Integer(), nullable=False),
    sa.Column('maxZugkraft', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('nr')
    )
    with op.batch_alter_table('triebwagen', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_triebwagen_spurweite'), ['spurweite'], unique=False)

    op.create_table('wagen',
    sa.Column('nr', sa.Integer(), nullable=False),
    sa.Column('spurweite', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('nr')
    )
    with op.batch_alter_table('wagen', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wagen_spurweite'), ['spurweite'], unique=False)

    op.create_table('wartung',
    sa.Column('wartungsNr', sa.Integer(), nullable=False),
    sa.Column('von', sa.DateTime(), nullable=False),
    sa.Column('bis', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('wartungsNr')
    )
    with op.batch_alter_table('wartung', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wartung_bis'), ['bis'], unique=False)
        batch_op.create_index(batch_op.f('ix_wartung_von'), ['von'], unique=False)

    op.create_table('wartungspersonal',
    sa.Column('mitarbeiterNr', sa.Integer(), nullable=False),
    sa.Column('svnr', sa.Integer(), nullable=False),
    sa.Column('vorname', sa.String(length=255), nullable=False),
    sa.Column('nachname', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('passwort', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('mitarbeiterNr')
    )
    with op.batch_alter_table('wartungspersonal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wartungspersonal_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_wartungspersonal_svnr'), ['svnr'], unique=True)

    op.create_table('zug',
    sa.Column('nr', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('nr')
    )
    op.create_table('zugpersonal',
    sa.Column('mitarbeiterNr', sa.Integer(), nullable=False),
    sa.Column('svnr', sa.Integer(), nullable=False),
    sa.Column('vorname', sa.String(length=255), nullable=False),
    sa.Column('nachname', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('passwort', sa.String(length=128), nullable=False),
    sa.Column('berufsbezeichnung', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('mitarbeiterNr')
    )
    with op.batch_alter_table('zugpersonal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zugpersonal_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_zugpersonal_svnr'), ['svnr'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zugpersonal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zugpersonal_svnr'))
        batch_op.drop_index(batch_op.f('ix_zugpersonal_email'))

    op.drop_table('zugpersonal')
    op.drop_table('zug')
    with op.batch_alter_table('wartungspersonal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wartungspersonal_svnr'))
        batch_op.drop_index(batch_op.f('ix_wartungspersonal_email'))

    op.drop_table('wartungspersonal')
    with op.batch_alter_table('wartung', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wartung_von'))
        batch_op.drop_index(batch_op.f('ix_wartung_bis'))

    op.drop_table('wartung')
    with op.batch_alter_table('wagen', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wagen_spurweite'))

    op.drop_table('wagen')
    with op.batch_alter_table('triebwagen', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_triebwagen_spurweite'))

    op.drop_table('triebwagen')
    with op.batch_alter_table('personenwagen', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_personenwagen_spurweite'))

    op.drop_table('personenwagen')
    with op.batch_alter_table('mitarbeiter', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mitarbeiter_svnr'))
        batch_op.drop_index(batch_op.f('ix_mitarbeiter_email'))

    op.drop_table('mitarbeiter')
    with op.batch_alter_table('administrator', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_administrator_svnr'))
        batch_op.drop_index(batch_op.f('ix_administrator_email'))

    op.drop_table('administrator')
    # ### end Alembic commands ###
