"""Ändern der Wartungstabelle (Hinzufügen des Felds datum und Änderung von 'von und 'bis'

Revision ID: 96e3b40b9567
Revises: 5c0711092e8c
Create Date: 2022-01-05 16:26:33.848798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96e3b40b9567'
down_revision = '5c0711092e8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wartung', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datum', sa.Date(), nullable=False))
        batch_op.drop_index('ix_wartung_bis')
        batch_op.drop_index('ix_wartung_von')
        batch_op.create_index(batch_op.f('ix_wartung_datum'), ['datum'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wartung', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wartung_datum'))
        batch_op.create_index('ix_wartung_von', ['von'], unique=False)
        batch_op.create_index('ix_wartung_bis', ['bis'], unique=False)
        batch_op.drop_column('datum')

    # ### end Alembic commands ###
