"""Mitarbeiter Tabellen

Revision ID: af5692bd5eb8
Revises: 
Create Date: 2021-12-11 19:11:34.801064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af5692bd5eb8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrator',
    sa.Column('mitarbeiterNr', sa.Integer(), nullable=False),
    sa.Column('svnr', sa.Integer(), nullable=False),
    sa.Column('vorname', sa.String(length=255), nullable=False),
    sa.Column('nachname', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('passwort', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('mitarbeiterNr')
    )
    with op.batch_alter_table('administrator', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_administrator_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_administrator_svnr'), ['svnr'], unique=True)

    op.create_table('mitarbeiter',
    sa.Column('mitarbeiterNr', sa.Integer(), nullable=False),
    sa.Column('svnr', sa.Integer(), nullable=False),
    sa.Column('vorname', sa.String(length=255), nullable=False),
    sa.Column('nachname', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('passwort', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('mitarbeiterNr')
    )
    with op.batch_alter_table('mitarbeiter', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mitarbeiter_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_mitarbeiter_svnr'), ['svnr'], unique=True)

    op.create_table('wartungspersonal',
    sa.Column('mitarbeiterNr', sa.Integer(), nullable=False),
    sa.Column('svnr', sa.Integer(), nullable=False),
    sa.Column('vorname', sa.String(length=255), nullable=False),
    sa.Column('nachname', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('passwort', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('mitarbeiterNr')
    )
    with op.batch_alter_table('wartungspersonal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wartungspersonal_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_wartungspersonal_svnr'), ['svnr'], unique=True)

    op.create_table('zugpersonal',
    sa.Column('mitarbeiterNr', sa.Integer(), nullable=False),
    sa.Column('svnr', sa.Integer(), nullable=False),
    sa.Column('vorname', sa.String(length=255), nullable=False),
    sa.Column('nachname', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('passwort', sa.String(length=128), nullable=False),
    sa.Column('berufsbezeichnung', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('mitarbeiterNr')
    )
    with op.batch_alter_table('zugpersonal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zugpersonal_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_zugpersonal_svnr'), ['svnr'], unique=True)

    op.drop_table('_alembic_tmp_zugpersonal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_zugpersonal',
    sa.Column('mitarbeiterNr', sa.INTEGER(), nullable=False),
    sa.Column('svnr', sa.INTEGER(), nullable=False),
    sa.Column('vorname', sa.VARCHAR(length=255), nullable=False),
    sa.Column('nachname', sa.VARCHAR(length=255), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('passwort', sa.VARCHAR(length=128), nullable=False),
    sa.Column('berufsbezeichnung', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('mitarbeiterNr')
    )
    with op.batch_alter_table('zugpersonal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zugpersonal_svnr'))
        batch_op.drop_index(batch_op.f('ix_zugpersonal_email'))

    op.drop_table('zugpersonal')
    with op.batch_alter_table('wartungspersonal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wartungspersonal_svnr'))
        batch_op.drop_index(batch_op.f('ix_wartungspersonal_email'))

    op.drop_table('wartungspersonal')
    with op.batch_alter_table('mitarbeiter', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mitarbeiter_svnr'))
        batch_op.drop_index(batch_op.f('ix_mitarbeiter_email'))

    op.drop_table('mitarbeiter')
    with op.batch_alter_table('administrator', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_administrator_svnr'))
        batch_op.drop_index(batch_op.f('ix_administrator_email'))

    op.drop_table('administrator')
    # ### end Alembic commands ###
