"""tours can have multiple intervals

Revision ID: 032c9e9c60d7
Revises: 21ef6f3fc8de
Create Date: 2021-12-22 15:37:47.249859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '032c9e9c60d7'
down_revision = '21ef6f3fc8de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interval', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tour_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_interval_tour_id_tour'), 'tour', ['tour_id'], ['id'])

    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tour_interval_interval', type_='foreignkey')
        batch_op.drop_column('interval')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interval', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_tour_interval_interval', 'interval', ['interval'], ['id'])

    with op.batch_alter_table('interval', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_interval_tour_id_tour'), type_='foreignkey')
        batch_op.drop_column('tour_id')

    # ### end Alembic commands ###
