"""added column days to keep old trips to system

Revision ID: 0c1673449402
Revises: 3410866d52a4
Create Date: 2022-01-03 16:47:20.167561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c1673449402'
down_revision = '3410866d52a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system', schema=None) as batch_op:
        batch_op.add_column(sa.Column('days_to_keep_old_trips', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system', schema=None) as batch_op:
        batch_op.drop_column('days_to_keep_old_trips')

    # ### end Alembic commands ###
