"""connected Trip and Interval

Revision ID: 21ef6f3fc8de
Revises: a64dbb94f07b
Create Date: 2021-12-22 14:49:33.057242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21ef6f3fc8de'
down_revision = 'a64dbb94f07b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interval_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_trip_interval_id_interval'), 'interval', ['interval_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_trip_interval_id_interval'), type_='foreignkey')
        batch_op.drop_column('interval_id')

    # ### end Alembic commands ###
