"""added weekdays column to interval

Revision ID: 3410866d52a4
Revises: fb451b9b065b
Create Date: 2022-01-03 15:34:36.830058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3410866d52a4'
down_revision = 'fb451b9b065b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interval', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weekdays', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interval', schema=None) as batch_op:
        batch_op.drop_column('weekdays')

    # ### end Alembic commands ###
