"""renamed column in TrainWarning

Revision ID: 3672eea09b93
Revises: 1d88e03130fe
Create Date: 2022-01-17 09:04:01.542881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3672eea09b93'
down_revision = '1d88e03130fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('train_warning', schema=None) as batch_op:
        batch_op.add_column(sa.Column('train_nr', sa.String(length=128), nullable=True))
        batch_op.drop_column('type')
        batch_op.drop_column('train')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('train_warning', schema=None) as batch_op:
        batch_op.add_column(sa.Column('train', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_column('train_nr')

    # ### end Alembic commands ###
