"""every tour now has own rushhours

Revision ID: 39f9c6b3e3f5
Revises: 
Create Date: 2022-01-06 13:57:46.660104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39f9c6b3e3f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rushhour', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tour_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_rushhour_system_id_system', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_rushhour_tour_id_tour'), 'tour', ['tour_id'], ['id'])
        batch_op.drop_column('system_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rushhour', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_rushhour_tour_id_tour'), type_='foreignkey')
        batch_op.create_foreign_key('fk_rushhour_system_id_system', 'system', ['system_id'], ['id'])
        batch_op.drop_column('tour_id')

    # ### end Alembic commands ###
