"""intervals now support minutes

Revision ID: 430a81a09d9d
Revises: 032c9e9c60d7
Create Date: 2021-12-24 10:44:35.300881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '430a81a09d9d'
down_revision = '032c9e9c60d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interval', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.Time(), nullable=True))
        batch_op.create_index(batch_op.f('ix_interval_end_time'), ['end_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_interval_start_time'), ['start_time'], unique=False)
        batch_op.drop_column('fromHour')
        batch_op.drop_column('toHour')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interval', schema=None) as batch_op:
        batch_op.add_column(sa.Column('toHour', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('fromHour', sa.INTEGER(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_interval_start_time'))
        batch_op.drop_index(batch_op.f('ix_interval_end_time'))
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###
