"""added warnings

Revision ID: 525d218d69ec
Revises: 39f9c6b3e3f5
Create Date: 2022-01-13 11:52:03.095671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '525d218d69ec'
down_revision = '39f9c6b3e3f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_warning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('msg', sa.String(length=512), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('system_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], name=op.f('fk_system_warning_system_id_system')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_warning'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_warning')
    # ### end Alembic commands ###
