"""renamed rushhour columns

Revision ID: 69fb789ab2eb
Revises: e2cecd671bdf
Create Date: 2021-12-25 22:00:46.684896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69fb789ab2eb'
down_revision = 'e2cecd671bdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rushhour', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.DateTime(), nullable=True))
        batch_op.drop_column('start')
        batch_op.drop_column('end')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rushhour', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('start', sa.DATETIME(), nullable=True))
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###
