"""added interval

Revision ID: 6c249aee908c
Revises: 6cc6743658f1
Create Date: 2021-12-11 15:29:36.730157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c249aee908c'
down_revision = '6cc6743658f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interval',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fromHour', sa.Integer(), nullable=True),
    sa.Column('toHour', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interval'))
    )
    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interval', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_tour_interval_interval'), 'interval', ['interval'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tour_interval_interval'), type_='foreignkey')
        batch_op.drop_column('interval')

    op.drop_table('interval')
    # ### end Alembic commands ###
