"""removed test

Revision ID: 6cc6743658f1
Revises: c99ca9615a98
Create Date: 2021-12-11 14:08:35.760907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cc6743658f1'
down_revision = 'c99ca9615a98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_test')
    )
    # ### end Alembic commands ###
