"""inital migration

Revision ID: 84a7afc3124b
Revises: 
Create Date: 2021-12-11 14:05:49.329482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84a7afc3124b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_employee_crew_id_crew'), 'crew', ['crew_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_employee_crew_id_crew'), type_='foreignkey')

    op.create_table('test',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
