"""added missing rushhour foreign key

Revision ID: e2cecd671bdf
Revises: 5db1e2edea06
Create Date: 2021-12-25 11:31:24.837951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2cecd671bdf'
down_revision = '5db1e2edea06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rushhour', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_rushhour_system_id_system'), 'system', ['system_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rushhour', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_rushhour_system_id_system'), type_='foreignkey')
        batch_op.drop_column('system_id')

    # ### end Alembic commands ###
