"""refactored trip date and time into datetime

Revision ID: fb451b9b065b
Revises: 98eb8640f4c2
Create Date: 2022-01-02 11:57:33.717997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb451b9b065b'
down_revision = '98eb8640f4c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_datetime', sa.DateTime(), nullable=True))
        batch_op.drop_index('ix_trip_date')
        batch_op.drop_index('ix_trip_time')
        batch_op.create_index(batch_op.f('ix_trip_start_datetime'), ['start_datetime'], unique=False)
        batch_op.drop_column('date')
        batch_op.drop_column('time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.DATE(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_trip_start_datetime'))
        batch_op.create_index('ix_trip_time', ['time'], unique=False)
        batch_op.create_index('ix_trip_date', ['date'], unique=False)
        batch_op.drop_column('start_datetime')

    # ### end Alembic commands ###
